linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/michaelahli/cegw
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: internal/ccxt/client.go
      linters:
        - gosec
      text: "G103: Use of unsafe calls"
    - linters:
        - staticcheck
      text: "SA1019:"

run:
  timeout: 5m
  go: '1.23'

issues:
  exclude-dirs:
    - gen
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
