version: 2
project_name: cegw

builds:
  - id: cegw
    binary: cegw
    main: ./cmd/cegw
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags: -s -w

archives:
  - id: default
    format: tar.gz
    files:
      - LICENSE
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: false

changelog:
  use: git
