version: 2
project_name: cegw

builds:
  - id: cegw
    binary: cegw
    main: ./cmd/cegw
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags: -s -w

archives:
  - id: unix
    format: tar.gz
    files:
      - LICENSE
    filters:
      exclude:
        - goos: windows
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

  - id: windows
    format: zip
    files:
      - LICENSE
    filters:
      only:
        - goos: windows
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

release:
  draft: false

changelog:
  use: git
