version: "3.9"

services:
  cegw:
    image: ghcr.io/michaelahli/cegw:latest
    container_name: cegw
    ports:
      - "8181:50051"
      - "8282:8080"
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      TIMEZONE: Asia/Jakarta
      SANDBOX_MODE: "false"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
