apiVersion: v1
kind: Service
metadata:
  name: {{ include "cegw.fullname" . }}-grpc
  labels:
    {{- include "cegw.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "cegw.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cegw.fullname" . }}-http
  labels:
    {{- include "cegw.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "cegw.selectorLabels" . | nindent 4 }}
